version: "2.2"

services:
    vault:
        build:
            dockerfile: .docker/Dockerfile
        user: "node"
        working_dir: /opt/castellum/vault
        command: npm run build
        volumes:
            - ./:/opt/castellum/vault
