name: test

on:
    push:
        branches:
            - main
    pull_request: ~

jobs:
    test:
        name: test
        runs-on: ubuntu-latest
        container:
            image: node:16-alpine
            env:
                NODE_ENV: development
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: install
              run: npm i

            - name: run tests
              run: npm run test

            - name: check format
              run: npx prettier --check ./

            - name: check format
              run: npx eslint --fix-dry-run ./
